version: 2.1



jobs:
  fail_job:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - return 1
 next_job:
  docker:
    - image: circleci/node:13.8.0
  steps:
    - echo "success"

workflows:
  my_workflow:
    jobs:
      - fail_job
      - next_job:
         when: on_fail 
